services:
  alpine-ssh:
    image: bigcapital_alpine:latest
    container_name: bigcapital_alpine
    ports:
      - "2222:22"  # Map to a specific port for easier debugging
    environment:
      - SSH_PUBLIC_KEY="YOUR_PUBLIC_KEY"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
